quarkus.http.port=8088
quarkus.langchain4j.ollama.chat-model.model-id=qwen3:1.7b
quarkus.langchain4j.ollama.timeout=5m
quarkus.langchain4j.ollama.embedding-model.model-id=nomic-embed-text

quarkus.langchain4j.chat-memory.type=message-window
quarkus.langchain4j.chat-memory.memory-window.max-messages=20

quarkus.langchain4j.log-requests=true
quarkus.langchain4j.log-responses=true
